### ISSUE TITLE
manpage tpnote.1.gz

### ISSUE THREAD

**Issue by 0323pin** [getreu/tp-note#10]
Hi,

I've finished packaging tp-note for NetBSD yesterday and would like to merge the package into our repositories.

Is it possible to add the man page (tpnote.1.gz) to the GitLab repository, so we don't need to fetch sources from different locations.
I see the tpnote.1.gz for v1.16.4 hosted at https://blog.getreu.net/projects/tp-note/
But, on the GitLab I can only find https://gitlab.com/getreu/tp-note/-/raw/master/docs/source/tpnote--manpage.md

Yes, it can be converted using pandoc but, that means adding an external build dependency to the package.
So, would you be willing to consider hosting tpnote.1.gz within the repository as well?

As for the package itself, it builds and runs just fine on NetBSD. I've been test using it for some hours and I couldn't find any issues.
Thank you for providing the software.

**Comment by getreu** [comment]
Resolved with `tp-note` v1.16.6.

**Comment by 0323pin** [comment]
@getreu Thanks!

If you don't mind, I'll keep the issue open until I've merged the package.

**Comment by 0323pin** [comment]
@getreu Merged into the main branch now. See, https://mail-index.netbsd.org/pkgsrc-changes/2022/05/20/msg254795.html for reference.

Would you mind adding install instructions for NetBSD to README.md?
If not, I can create a pull-request here on GitHub if it helps. Personally, I use codeberg and not github so I'd prefer if I don't have to create a GitLab account also,
Ok?

**Comment by getreu** [comment]
> Would you mind adding install instructions for NetBSD to README.md?
> I can create a pull-request here on GitHub if it helps.

Both are welcome.

**Comment by getreu** [comment]
Hallo @0323pin ,
there some little breaking changes in v1.18.0: 
* No more `.gz` files in the repository, please use [man/man1/tpnote.1](https://github.com/getreu/tp-note/blob/master/docs/build/man/man1/tpnote.1) instead and gzip it yourself.
* The code is split into 2 crates: `tp-note` and `tpnote-lib` (both hosted in one repository [getreu/tp-note](https://github.com/getreu/tp-note)) . However, this does not change the compilation: just type: `cargo build --release` in the root dir of the project as usual.

**Comment by 0323pin** [comment]
@getreu Was this re-opened because of the change from `tpnote.1.gz` to `tp.note.1`?
If so, I did catch the change and have actually merged 1.18.1 yesterday, https://mail-index.netbsd.org/pkgsrc-changes/2022/10/21/msg262335.html

Also, I caught the the split into two crates. All good, don't worry.
Thanks for reaching out and explaining.
Feel free to close it.

**Comment by getreu** [comment]
> Was this re-opened because of the change from tpnote.1.gz to tp.note.1?
Yes. 
> If so, I did catch the change and have actually merged 1.18.1 yesterday
Thank you.
