### ISSUE TITLE
Not support image in clipboard?

### ISSUE THREAD

**Issue by b1tg** [getreu/tp-note#15]
os: win11
test version: v1.20.1

**Comment by getreu** [comment]
Currently, Tp-Note does not read images from the clipboard. I actually like the idea, although it is not trivial to implement. But it is definitely doable: 
* [ ] Investigate what image format is delivered for the different OSs (Linux, Mac, Win).
* [ ] Add some image processing.
* [ ] Add another template.

Thank for the inspiration how to develop Tp-Note further.

**Comment by getreu** [comment]
After some consideration, I came to the conclusion that the above workflow is better supported by a file editor plugin. Tp-Note focuses on (clipboard) text analysis.
