### ISSUE TITLE
shorter binary name

### ISSUE THREAD

**Issue by getreu** [getreu/tp-note#7]
When [Tp-Note is unsed on the console](https://blog.getreu.net/projects/tp-note/tp-note--manual.html#note-taking-for-system-administrators-and-console-lovers), one has to write the binary name `tp-note` a lot. Here, the `-` is especially annoying, because it inhibits autocomplete.

Tp-Note should have a shorter binary name, maybe `tpnote` or `tpn`?
Are there any widely used `tpn` applications out there?

**Comment by midnightexigent** [comment]
on Arch Linux here, there are no known package (AUR included) that provide a binary named `tpn`

**Comment by getreu** [comment]
Yes, I am still waiting for [Tracking Issue for different-binary-name · Issue #9778 · rust-lang/cargo](https://github.com/rust-lang/cargo/issues/9778) to be stabilized. At the moment it only works with unstable `cargo`.

**Comment by midnightexigent** [comment]
Hmm, not sure why you would need that feature as `tpn` is a perfectly valid name. I just tried adding the following in `Cargo.toml` and it worked. Isn't that sufficient ? 

```toml
[[bin]]
name = "tpn"
path = "src/main.rs"
```

**Comment by getreu** [comment]
Thank you. I wil check this out.

**Comment by getreu** [comment]
Solved with: [Release v1.15.0: Rename binaries and installer packages to `tpnote` · getreu/tp-note](https://github.com/getreu/tp-note/releases/tag/v1.15.0)
